import test from 'node:test';
import assert from 'node:assert/strict';
import {TrackingStore} from './tracking-store.mjs';
import {createTrackingServer} from './tracking.mjs';

test('customer sessions scope fleet, commands, fences, alerts, links and relay access',async t=>{
  const store=new TrackingStore(':memory:');t.after(()=>store.close());
  const a=store.createCustomer({name:'Alpha Fleet',email:'alpha@example.test'});
  const b=store.createCustomer({name:'Beta Fleet',email:'beta@example.test'});
  const aDevice=store.createDevice({name:'A vehicle',model:'Mobile'},a.customer.id).device;
  const bDevice=store.createDevice({name:'B vehicle',model:'Mobile'},b.customer.id).device;
  const adminDevice=store.createDevice({name:'Admin vehicle',model:'Mobile'}).device;
  store.alert(aDevice.id,'offline','A only');store.alert(bDevice.id,'offline','B only');
  const server=createTrackingServer({store,adminToken:'customer-test-admin-secret-12345',bridge:{state:{configured:false,connected:false},sync:async()=>{} }});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>{server.close(resolve);server.closeAllConnections()}));
  const base=`http://127.0.0.1:${server.address().port}/api/gps`;
  const request=(path,options={})=>fetch(base+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});
  const login=async user=>{
    const r=await request('/customers/session',{method:'POST',body:JSON.stringify({email:user.customer.email,password:user.password})});
    assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];
  };
  const aCookie=await login(a),bCookie=await login(b);
  const as=(cookie,path,method='GET',body)=>request(path,{method,headers:{cookie},...(body?{body:JSON.stringify(body)}:{})});
  const created=await (await as(aCookie,'/devices','POST',{name:'A phone',model:'Mobile'})).json();
  assert.equal(created.device.tenantId,a.customer.id);
  const aState=await (await as(aCookie,'/state')).json();
  assert.deepEqual(aState.devices.map(d=>d.name).sort(),['A phone','A vehicle']);assert.deepEqual(aState.alerts.map(x=>x.deviceName),['A vehicle']);
  const bState=await (await as(bCookie,'/state')).json();assert.deepEqual(bState.devices.map(d=>d.name),['B vehicle']);
  assert.equal((await as(aCookie,`/devices/${bDevice.id}/driver-link`)).status,404);
  assert.equal((await as(aCookie,`/devices/${adminDevice.id}/ping`,'POST',{})).status,404);
  assert.equal((await as(aCookie,`/devices/${bDevice.id}/relay`)).status,404);
  assert.equal((await as(aCookie,'/customers')).status,403);
  const fence=await (await as(aCookie,'/fences','POST',{name:'A yard',latitude:18.5,longitude:73.8,radius:500})).json();
  assert.equal((await (await as(bCookie,'/state')).json()).fences.length,0);
  assert.equal((await as(bCookie,`/fences/${fence.id}`,'DELETE')).status,404);
  const alertId=aState.alerts[0].id;
  assert.equal((await as(bCookie,`/alerts/${alertId}/ack`,'POST',{})).status,404);
  assert.equal((await as(aCookie,`/alerts/${alertId}/ack`,'POST',{})).status,200);
  const link=await (await as(aCookie,`/devices/${aDevice.id}/driver-link`,'POST',{})).json();
  const join=await request('/sender/join',{method:'POST',body:JSON.stringify({code:link.code})});
  assert.equal(join.status,200,'Driver link remains scoped to its device without customer login.');
  const adminLogin=await request('/session',{method:'POST',body:JSON.stringify({token:'customer-test-admin-secret-12345'})});
  const adminCookie=adminLogin.headers.get('set-cookie').split(';')[0];
  assert.equal((await (await as(adminCookie,'/customers')).json()).customers.length,2);
  assert.deepEqual((await (await as(adminCookie,'/state')).json()).devices.map(d=>d.name),['Admin vehicle']);
  const reset=await (await as(adminCookie,`/customers/${a.customer.id}/reset`,'POST',{})).json();
  assert.equal((await as(aCookie,'/state')).status,401);
  assert.equal((await request('/customers/session',{method:'POST',body:JSON.stringify({email:a.customer.email,password:a.password})})).status,401);
  assert.equal((await request('/customers/session',{method:'POST',body:JSON.stringify({email:a.customer.email,password:reset.password})})).status,200);
  assert.equal((await as(adminCookie,`/customers/${b.customer.id}/access`,'PUT',{enabled:false})).status,200);
  assert.equal((await as(bCookie,'/state')).status,401);
  assert.equal((await request('/customers/session',{method:'POST',body:JSON.stringify({email:b.customer.email,password:b.password})})).status,401);
});
