import {createServer} from 'node:http';
import {readFileSync,writeFileSync,existsSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
const required=['SANDBOX_API_KEY','SANDBOX_API_SECRET','EWB_USERNAME','EWB_PASSWORD','EWB_GSTIN'];
const origin='http://127.0.0.1:5173';
export function checkResponse(body){if(body.code&&body.code!==200||String(body.data?.status)==='0'||String(body.data?.Status)==='0'||body.data?.error)throw new Error('Provider rejected request: '+String(body.data?.error?.errorCodes||body.code||'authentication failed'));return body}
async function request(path,headers,body){const r=await fetch('https://api.sandbox.co.in'+path,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':process.env.SANDBOX_API_KEY,'x-api-version':'1.0.0',...headers},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(25000)});if(!r.ok)throw new Error('Provider HTTP '+r.status);return checkResponse(await r.json())}
async function session(){const a=await request('/authenticate',{'x-api-secret':process.env.SANDBOX_API_SECRET});if(!a.data?.access_token)throw new Error('Sandbox authentication returned no token');const b=await request('/gst/compliance/e-way-bill/tax-payer/authenticate',{authorization:a.data.access_token,'x-source':'primary'},{username:process.env.EWB_USERNAME,password:process.env.EWB_PASSWORD,gstin:process.env.EWB_GSTIN});if(!b.data?.access_token)throw new Error('E-way bill authentication returned no token');return b.data.access_token}
export function validateBill(b){if(!b||typeof b!=='object'||Array.isArray(b))throw new Error('Invalid bill');for(const key of ['supplyType','subSupplyType','docType','docNo','docDate','fromGstin','toGstin','fromPincode','toPincode','fromStateCode','toStateCode','actFromStateCode','actToStateCode','totalValue','totInvValue','transactionType'])if(b[key]===undefined||b[key]==='')throw new Error('Missing '+key);if(!Array.isArray(b.itemList)||!b.itemList.length)throw new Error('At least one goods item is required');if(!/^\d{2}\/\d{2}\/\d{4}$/.test(b.docDate))throw new Error('docDate must use DD/MM/YYYY');return b}
const journalDir=fileURLToPath(new URL('./private/',import.meta.url));
export const server=createServer(async(req,res)=>{const send=(code,data)=>{res.writeHead(code,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data))};if(req.headers.host!==`127.0.0.1:${server.address().port}`)return send(403,{error:'Local access only'});if(req.method==='GET'&&req.url==='/api/eway/status')return send(200,{provider:'Sandbox.co.in',configured:required.every(k=>process.env[k]),missing:required.filter(k=>!process.env[k]),generationEnabled:process.env.EWB_ENABLE_GENERATION==='true'});if(req.method!=='POST'||!['/api/eway/connect','/api/eway/generate'].includes(req.url))return send(404,{error:'Not found'});if(req.headers.origin!==origin||req.headers['x-waypoint-request']!=='1')return send(403,{error:'Invalid request origin'});if(required.some(k=>!process.env[k]))return send(503,{error:'Configure server environment credentials first'});try{let text='';for await(const chunk of req){text+=chunk;if(text.length>131072)return send(413,{error:'Request too large'})}const body=JSON.parse(text||'{}');if(req.url==='/api/eway/connect'){await session();return send(200,{connected:true,provider:'Sandbox.co.in'})}if(process.env.EWB_ENABLE_GENERATION!=='true')return send(403,{error:'Generation disabled. Configure and approve live access first.'});if(body.confirmed!==true)return send(400,{error:'Explicit reviewed-bill confirmation required'});const bill=validateBill(body.bill);const key=createHash('sha256').update(JSON.stringify([bill.fromGstin,bill.docType,bill.docNo,bill.docDate])).digest('hex');mkdirSync(journalDir,{recursive:true,mode:0o700});const path=journalDir+key+'.json';if(existsSync(path)){const previous=JSON.parse(readFileSync(path,'utf8'));return send(409,{error:'A submission already exists for this invoice. Verify on provider before resubmitting.',result:previous.result})}const token=await session();writeFileSync(path,JSON.stringify({state:'pending',at:new Date().toISOString()}),{flag:'wx',mode:0o600});try{const result=await request('/gst/compliance/e-way-bill/consignor/bill',{authorization:token},bill);writeFileSync(path,JSON.stringify({state:'received',result}),{mode:0o600});return send(200,result)}catch{writeFileSync(path,JSON.stringify({state:'unknown',at:new Date().toISOString()}),{mode:0o600});return send(502,{error:'Submission outcome needs verification on provider. Automatic retry blocked.'})}}catch(error){return send(400,{error:error instanceof Error?error.message:'Request failed'})}});
if(process.argv[1]===fileURLToPath(import.meta.url))server.listen(5174,'127.0.0.1',()=>console.log('Waypoint Sandbox adapter on 127.0.0.1:5174'));
